name: multi-stage-variable-expansion-broken

variables:
- name: 'subscriptionConnection3'
  value: 'internal-azure-subscription'


stages:
- stage: Stage
  displayName: Stage

  # Global variables shared by all jobs
  variables:
  - name: 'subscriptionConnection2'
    value: 'internal-azure-subscription'

  jobs:
  - job: 'Repro'
    displayName: 'Repro'
    condition: succeeded()
    timeoutInMinutes: $[ variables['jobTimeOutMinutes'] ]

    pool:
      vmImage: 'ubuntu-latest'

    workspace:
      clean: all

    steps:
      - pwsh: |
          Write-Host "Connection name: $(subscriptionConnection2)"
        displayName: 'Expand stage level variable'

      # Broken
      # There was a resource authorization issue: "The pipeline is not valid. Job Repro: Step useConnectionB input connectedServiceNameARM references service connection $(subscriptionConnection2) which could not be found. The service connection does not exist or has not been authorized for use. For authorization details, refer to https://aka.ms/yamlauthz."
      - task: AzureCLI@2
        displayName: 'Access service connection through stage level variable'
        enabled: false
        name: useConnectionB
        condition: succeededOrFailed()
        inputs:
          azureSubscription: '$(subscriptionConnection2)'
          scriptType: pscore
          scriptLocation: inlineScript
          inlineScript: |
            az account show
          addSpnToEnvironment: true
          useGlobalConfig: true
          failOnStandardError: true
    
      - pwsh: |
          Write-Host "Connection name: $(subscriptionConnection3)"
        displayName: 'Expand pipeline level variable'

      # Works!
      - task: AzureCLI@2
        displayName: 'Access service connection through pipeline level variable'
        enabled: true
        name: useConnectionC
        condition: succeededOrFailed()
        inputs:
          azureSubscription: '$(subscriptionConnection3)'
          scriptType: pscore
          scriptLocation: inlineScript
          inlineScript: |
            az account show
          addSpnToEnvironment: true
          useGlobalConfig: true
          failOnStandardError: true
