name: multi-stage-variable-expansion-broken

stages:
- stage: Stage
  displayName: Stage

  # Global variables shared by all jobs
  variables:
  - group: 'vdc'
  - group: 'vdc-ci'
  - name: 'subscriptionConnection1'
    value: 'internal-azure-subscription'

  jobs:
  - job: 'Prepare'
    displayName: 'Prepare'
    condition: succeeded()
    timeoutInMinutes: $[ variables['jobTimeOutMinutes'] ]

    pool:
      vmImage: 'ubuntu-latest'

    workspace:
      clean: all

    steps:
    #   - task: AzureCLI@2
    #     displayName: 'Access service connection through stage level variable group'
    #     enabled: true
    #     name: useConnectionA
    #     inputs:
    #       azureSubscription: '$(subscriptionConnection)'
    #       scriptType: pscore
    #       scriptLocation: inlineScript
    #       inlineScript: |
    #         az account show
    #       addSpnToEnvironment: true
    #       useGlobalConfig: true
    #       failOnStandardError: true

      - task: AzureCLI@2
        displayName: 'Access service connection through stage level variable'
        enabled: true
        name: useConnectionB
        condition: succeededOrFailed()
        inputs:
          azureSubscription: '$(subscriptionConnection1)'
          scriptType: pscore
          scriptLocation: inlineScript
          inlineScript: |
            az account show
          addSpnToEnvironment: true
          useGlobalConfig: true
          failOnStandardError: true
    