name: multi-stage-variable-expansion-broken

variables:
- name: 'pipelineConnectionVariable'
  value: 'internal-azure-subscription'


stages:
- stage: Stage
  displayName: Stage

  # Global variables shared by all jobs
  variables:
  - name: 'stageConnectionVariable'
    value: 'internal-azure-subscription'

  jobs:
  - job: 'Repro'
    displayName: 'Repro'
    condition: succeeded()
    timeoutInMinutes: $[ variables['jobTimeOutMinutes'] ]

    pool:
      vmImage: 'ubuntu-latest'

    variables:
      - name: 'jobConnectionVariable'
        value: 'internal-azure-subscription'
        
    steps:
      - pwsh: |
          Write-Host "Pipeline connection name: $(pipelineConnectionVariable)"
        displayName: 'Expand pipeline level variable'

      # Works!
      - task: AzureCLI@2
        displayName: 'Access service connection through pipeline level variable'
        enabled: true
        name: usePipelineConnectionVariable
        condition: succeededOrFailed()
        inputs:
          azureSubscription: '$(pipelineConnectionVariable)'
          scriptType: pscore
          scriptLocation: inlineScript
          inlineScript: |
            az account show
          addSpnToEnvironment: true
          useGlobalConfig: true
          failOnStandardError: true

      - pwsh: |
          Write-Host "Job connection name: $(jobConnectionVariable)"
        displayName: 'Expand job level variable'

      - task: AzureCLI@2
        displayName: 'Access service connection through job level variable'
        enabled: true
        name: useStageConnectionVariable
        condition: succeededOrFailed()
        inputs:
          azureSubscription: '$(jobConnectionVariable)'
          scriptType: pscore
          scriptLocation: inlineScript
          inlineScript: |
            az account show
          addSpnToEnvironment: true
          useGlobalConfig: true
          failOnStandardError: true
    
      - pwsh: |
          Write-Host "Stage connection name: $(stageConnectionVariable)"
        displayName: 'Expand stage level variable'

      # # Broken
      # # There was a resource authorization issue: "The pipeline is not valid. Job Repro: Step useConnectionB input connectedServiceNameARM references service connection $(subscriptionConnection2) which could not be found. The service connection does not exist or has not been authorized for use. For authorization details, refer to https://aka.ms/yamlauthz."
      # - task: AzureCLI@2
      #   displayName: 'Access service connection through stage level variable'
      #   enabled: true
      #   name: useStageConnectionVariable
      #   condition: succeededOrFailed()
      #   inputs:
      #     azureSubscription: '$(stageConnectionVariable)'
      #     scriptType: pscore
      #     scriptLocation: inlineScript
      #     inlineScript: |
      #       az account show
      #     addSpnToEnvironment: true
      #     useGlobalConfig: true
      #     failOnStandardError: true
    